name: app workflow
on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    uses: kp3074/reusable-workflow/.github/workflows/cicd.yaml@main
    with:
      config-path: TESTGITHUBACTION
